/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppThoughtsRouteImport } from './routes/app.thoughts'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScratchRouteImport } from './routes/app.scratch'
import { Route as AppPrivateRouteImport } from './routes/app.private'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMoodRouteImport } from './routes/app.mood'
import { Route as AppMemoriesRouteImport } from './routes/app.memories'
import { Route as AppLettersRouteImport } from './routes/app.letters'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppHabitsRouteImport } from './routes/app.habits'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppExportRouteImport } from './routes/app.export'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCapsulesRouteImport } from './routes/app.capsules'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppNotesIndexRouteImport } from './routes/app.notes.index'
import { Route as AppFarewellIndexRouteImport } from './routes/app.farewell.index'
import { Route as AppThoughtsIdRouteImport } from './routes/app.thoughts.$id'
import { Route as AppTasksIdRouteImport } from './routes/app.tasks.$id'
import { Route as AppTagsTagRouteImport } from './routes/app.tags.$tag'
import { Route as AppNotesNewRouteImport } from './routes/app.notes.new'
import { Route as AppNotesIdRouteImport } from './routes/app.notes.$id'
import { Route as AppMemoriesIdRouteImport } from './routes/app.memories.$id'
import { Route as AppLettersIdRouteImport } from './routes/app.letters.$id'
import { Route as AppJournalIdRouteImport } from './routes/app.journal.$id'
import { Route as AppFarewellVoiceRouteImport } from './routes/app.farewell.voice'
import { Route as AppFarewellCustomRouteImport } from './routes/app.farewell.custom'
import { Route as AppCapsulesIdRouteImport } from './routes/app.capsules.$id'
import { Route as AppFarewellPickCategoryRouteImport } from './routes/app.farewell.pick.$category'
import { Route as AppFarewellEntityIdRouteImport } from './routes/app.farewell.$entity.$id'
import { Route as AppFarewellPreviewEntityIdRouteImport } from './routes/app.farewell.preview.$entity.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppThoughtsRoute = AppThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScratchRoute = AppScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateRoute = AppPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodRoute = AppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppLettersRoute = AppLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCapsulesRoute = AppCapsulesRouteImport.update({
  id: '/capsules',
  path: '/capsules',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppFarewellIndexRoute = AppFarewellIndexRouteImport.update({
  id: '/farewell/',
  path: '/farewell/',
  getParentRoute: () => AppRoute,
} as any)
const AppThoughtsIdRoute = AppThoughtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppThoughtsRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTagsTagRoute = AppTagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppNotesIdRoute = AppNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppMemoriesIdRoute = AppMemoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMemoriesRoute,
} as any)
const AppLettersIdRoute = AppLettersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLettersRoute,
} as any)
const AppJournalIdRoute = AppJournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppFarewellVoiceRoute = AppFarewellVoiceRouteImport.update({
  id: '/farewell/voice',
  path: '/farewell/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppFarewellCustomRoute = AppFarewellCustomRouteImport.update({
  id: '/farewell/custom',
  path: '/farewell/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppCapsulesIdRoute = AppCapsulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCapsulesRoute,
} as any)
const AppFarewellPickCategoryRoute = AppFarewellPickCategoryRouteImport.update({
  id: '/farewell/pick/$category',
  path: '/farewell/pick/$category',
  getParentRoute: () => AppRoute,
} as any)
const AppFarewellEntityIdRoute = AppFarewellEntityIdRouteImport.update({
  id: '/farewell/$entity/$id',
  path: '/farewell/$entity/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFarewellPreviewEntityIdRoute =
  AppFarewellPreviewEntityIdRouteImport.update({
    id: '/farewell/preview/$entity/$id',
    path: '/farewell/preview/$entity/$id',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capsules': typeof AppCapsulesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/export': typeof AppExportRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/letters': typeof AppLettersRouteWithChildren
  '/app/memories': typeof AppMemoriesRouteWithChildren
  '/app/mood': typeof AppMoodRoute
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/private': typeof AppPrivateRoute
  '/app/scratch': typeof AppScratchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/thoughts': typeof AppThoughtsRouteWithChildren
  '/app/timeline': typeof AppTimelineRoute
  '/app/': typeof AppIndexRoute
  '/app/capsules/$id': typeof AppCapsulesIdRoute
  '/app/farewell/custom': typeof AppFarewellCustomRoute
  '/app/farewell/voice': typeof AppFarewellVoiceRoute
  '/app/journal/$id': typeof AppJournalIdRoute
  '/app/letters/$id': typeof AppLettersIdRoute
  '/app/memories/$id': typeof AppMemoriesIdRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/thoughts/$id': typeof AppThoughtsIdRoute
  '/app/farewell/': typeof AppFarewellIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/farewell/$entity/$id': typeof AppFarewellEntityIdRoute
  '/app/farewell/pick/$category': typeof AppFarewellPickCategoryRoute
  '/app/farewell/preview/$entity/$id': typeof AppFarewellPreviewEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capsules': typeof AppCapsulesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/export': typeof AppExportRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/letters': typeof AppLettersRouteWithChildren
  '/app/memories': typeof AppMemoriesRouteWithChildren
  '/app/mood': typeof AppMoodRoute
  '/app/private': typeof AppPrivateRoute
  '/app/scratch': typeof AppScratchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/thoughts': typeof AppThoughtsRouteWithChildren
  '/app/timeline': typeof AppTimelineRoute
  '/app': typeof AppIndexRoute
  '/app/capsules/$id': typeof AppCapsulesIdRoute
  '/app/farewell/custom': typeof AppFarewellCustomRoute
  '/app/farewell/voice': typeof AppFarewellVoiceRoute
  '/app/journal/$id': typeof AppJournalIdRoute
  '/app/letters/$id': typeof AppLettersIdRoute
  '/app/memories/$id': typeof AppMemoriesIdRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/thoughts/$id': typeof AppThoughtsIdRoute
  '/app/farewell': typeof AppFarewellIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/farewell/$entity/$id': typeof AppFarewellEntityIdRoute
  '/app/farewell/pick/$category': typeof AppFarewellPickCategoryRoute
  '/app/farewell/preview/$entity/$id': typeof AppFarewellPreviewEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capsules': typeof AppCapsulesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/export': typeof AppExportRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/letters': typeof AppLettersRouteWithChildren
  '/app/memories': typeof AppMemoriesRouteWithChildren
  '/app/mood': typeof AppMoodRoute
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/private': typeof AppPrivateRoute
  '/app/scratch': typeof AppScratchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/thoughts': typeof AppThoughtsRouteWithChildren
  '/app/timeline': typeof AppTimelineRoute
  '/app/': typeof AppIndexRoute
  '/app/capsules/$id': typeof AppCapsulesIdRoute
  '/app/farewell/custom': typeof AppFarewellCustomRoute
  '/app/farewell/voice': typeof AppFarewellVoiceRoute
  '/app/journal/$id': typeof AppJournalIdRoute
  '/app/letters/$id': typeof AppLettersIdRoute
  '/app/memories/$id': typeof AppMemoriesIdRoute
  '/app/notes/$id': typeof AppNotesIdRoute
  '/app/notes/new': typeof AppNotesNewRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/thoughts/$id': typeof AppThoughtsIdRoute
  '/app/farewell/': typeof AppFarewellIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/farewell/$entity/$id': typeof AppFarewellEntityIdRoute
  '/app/farewell/pick/$category': typeof AppFarewellPickCategoryRoute
  '/app/farewell/preview/$entity/$id': typeof AppFarewellPreviewEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/achievements'
    | '/app/calendar'
    | '/app/capsules'
    | '/app/dashboard'
    | '/app/export'
    | '/app/favorites'
    | '/app/habits'
    | '/app/home'
    | '/app/insights'
    | '/app/journal'
    | '/app/letters'
    | '/app/memories'
    | '/app/mood'
    | '/app/notes'
    | '/app/private'
    | '/app/scratch'
    | '/app/settings'
    | '/app/tasks'
    | '/app/thoughts'
    | '/app/timeline'
    | '/app/'
    | '/app/capsules/$id'
    | '/app/farewell/custom'
    | '/app/farewell/voice'
    | '/app/journal/$id'
    | '/app/letters/$id'
    | '/app/memories/$id'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/tags/$tag'
    | '/app/tasks/$id'
    | '/app/thoughts/$id'
    | '/app/farewell/'
    | '/app/notes/'
    | '/app/farewell/$entity/$id'
    | '/app/farewell/pick/$category'
    | '/app/farewell/preview/$entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/achievements'
    | '/app/calendar'
    | '/app/capsules'
    | '/app/dashboard'
    | '/app/export'
    | '/app/favorites'
    | '/app/habits'
    | '/app/home'
    | '/app/insights'
    | '/app/journal'
    | '/app/letters'
    | '/app/memories'
    | '/app/mood'
    | '/app/private'
    | '/app/scratch'
    | '/app/settings'
    | '/app/tasks'
    | '/app/thoughts'
    | '/app/timeline'
    | '/app'
    | '/app/capsules/$id'
    | '/app/farewell/custom'
    | '/app/farewell/voice'
    | '/app/journal/$id'
    | '/app/letters/$id'
    | '/app/memories/$id'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/tags/$tag'
    | '/app/tasks/$id'
    | '/app/thoughts/$id'
    | '/app/farewell'
    | '/app/notes'
    | '/app/farewell/$entity/$id'
    | '/app/farewell/pick/$category'
    | '/app/farewell/preview/$entity/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/achievements'
    | '/app/calendar'
    | '/app/capsules'
    | '/app/dashboard'
    | '/app/export'
    | '/app/favorites'
    | '/app/habits'
    | '/app/home'
    | '/app/insights'
    | '/app/journal'
    | '/app/letters'
    | '/app/memories'
    | '/app/mood'
    | '/app/notes'
    | '/app/private'
    | '/app/scratch'
    | '/app/settings'
    | '/app/tasks'
    | '/app/thoughts'
    | '/app/timeline'
    | '/app/'
    | '/app/capsules/$id'
    | '/app/farewell/custom'
    | '/app/farewell/voice'
    | '/app/journal/$id'
    | '/app/letters/$id'
    | '/app/memories/$id'
    | '/app/notes/$id'
    | '/app/notes/new'
    | '/app/tags/$tag'
    | '/app/tasks/$id'
    | '/app/thoughts/$id'
    | '/app/farewell/'
    | '/app/notes/'
    | '/app/farewell/$entity/$id'
    | '/app/farewell/pick/$category'
    | '/app/farewell/preview/$entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/thoughts': {
      id: '/app/thoughts'
      path: '/thoughts'
      fullPath: '/app/thoughts'
      preLoaderRoute: typeof AppThoughtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scratch': {
      id: '/app/scratch'
      path: '/scratch'
      fullPath: '/app/scratch'
      preLoaderRoute: typeof AppScratchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/private': {
      id: '/app/private'
      path: '/private'
      fullPath: '/app/private'
      preLoaderRoute: typeof AppPrivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mood': {
      id: '/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AppMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memories': {
      id: '/app/memories'
      path: '/memories'
      fullPath: '/app/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/letters': {
      id: '/app/letters'
      path: '/letters'
      fullPath: '/app/letters'
      preLoaderRoute: typeof AppLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habits': {
      id: '/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/export': {
      id: '/app/export'
      path: '/export'
      fullPath: '/app/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capsules': {
      id: '/app/capsules'
      path: '/capsules'
      fullPath: '/app/capsules'
      preLoaderRoute: typeof AppCapsulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/'
      fullPath: '/app/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/farewell/': {
      id: '/app/farewell/'
      path: '/farewell'
      fullPath: '/app/farewell/'
      preLoaderRoute: typeof AppFarewellIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/thoughts/$id': {
      id: '/app/thoughts/$id'
      path: '/$id'
      fullPath: '/app/thoughts/$id'
      preLoaderRoute: typeof AppThoughtsIdRouteImport
      parentRoute: typeof AppThoughtsRoute
    }
    '/app/tasks/$id': {
      id: '/app/tasks/$id'
      path: '/$id'
      fullPath: '/app/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/app/tags/$tag': {
      id: '/app/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/app/tags/$tag'
      preLoaderRoute: typeof AppTagsTagRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/new': {
      id: '/app/notes/new'
      path: '/new'
      fullPath: '/app/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/notes/$id': {
      id: '/app/notes/$id'
      path: '/$id'
      fullPath: '/app/notes/$id'
      preLoaderRoute: typeof AppNotesIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/memories/$id': {
      id: '/app/memories/$id'
      path: '/$id'
      fullPath: '/app/memories/$id'
      preLoaderRoute: typeof AppMemoriesIdRouteImport
      parentRoute: typeof AppMemoriesRoute
    }
    '/app/letters/$id': {
      id: '/app/letters/$id'
      path: '/$id'
      fullPath: '/app/letters/$id'
      preLoaderRoute: typeof AppLettersIdRouteImport
      parentRoute: typeof AppLettersRoute
    }
    '/app/journal/$id': {
      id: '/app/journal/$id'
      path: '/$id'
      fullPath: '/app/journal/$id'
      preLoaderRoute: typeof AppJournalIdRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/app/farewell/voice': {
      id: '/app/farewell/voice'
      path: '/farewell/voice'
      fullPath: '/app/farewell/voice'
      preLoaderRoute: typeof AppFarewellVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farewell/custom': {
      id: '/app/farewell/custom'
      path: '/farewell/custom'
      fullPath: '/app/farewell/custom'
      preLoaderRoute: typeof AppFarewellCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capsules/$id': {
      id: '/app/capsules/$id'
      path: '/$id'
      fullPath: '/app/capsules/$id'
      preLoaderRoute: typeof AppCapsulesIdRouteImport
      parentRoute: typeof AppCapsulesRoute
    }
    '/app/farewell/pick/$category': {
      id: '/app/farewell/pick/$category'
      path: '/farewell/pick/$category'
      fullPath: '/app/farewell/pick/$category'
      preLoaderRoute: typeof AppFarewellPickCategoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farewell/$entity/$id': {
      id: '/app/farewell/$entity/$id'
      path: '/farewell/$entity/$id'
      fullPath: '/app/farewell/$entity/$id'
      preLoaderRoute: typeof AppFarewellEntityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farewell/preview/$entity/$id': {
      id: '/app/farewell/preview/$entity/$id'
      path: '/farewell/preview/$entity/$id'
      fullPath: '/app/farewell/preview/$entity/$id'
      preLoaderRoute: typeof AppFarewellPreviewEntityIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCapsulesRouteChildren {
  AppCapsulesIdRoute: typeof AppCapsulesIdRoute
}

const AppCapsulesRouteChildren: AppCapsulesRouteChildren = {
  AppCapsulesIdRoute: AppCapsulesIdRoute,
}

const AppCapsulesRouteWithChildren = AppCapsulesRoute._addFileChildren(
  AppCapsulesRouteChildren,
)

interface AppJournalRouteChildren {
  AppJournalIdRoute: typeof AppJournalIdRoute
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalIdRoute: AppJournalIdRoute,
}

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
)

interface AppLettersRouteChildren {
  AppLettersIdRoute: typeof AppLettersIdRoute
}

const AppLettersRouteChildren: AppLettersRouteChildren = {
  AppLettersIdRoute: AppLettersIdRoute,
}

const AppLettersRouteWithChildren = AppLettersRoute._addFileChildren(
  AppLettersRouteChildren,
)

interface AppMemoriesRouteChildren {
  AppMemoriesIdRoute: typeof AppMemoriesIdRoute
}

const AppMemoriesRouteChildren: AppMemoriesRouteChildren = {
  AppMemoriesIdRoute: AppMemoriesIdRoute,
}

const AppMemoriesRouteWithChildren = AppMemoriesRoute._addFileChildren(
  AppMemoriesRouteChildren,
)

interface AppNotesRouteChildren {
  AppNotesIdRoute: typeof AppNotesIdRoute
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesIdRoute: AppNotesIdRoute,
  AppNotesNewRoute: AppNotesNewRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksIdRoute: typeof AppTasksIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksIdRoute: AppTasksIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppThoughtsRouteChildren {
  AppThoughtsIdRoute: typeof AppThoughtsIdRoute
}

const AppThoughtsRouteChildren: AppThoughtsRouteChildren = {
  AppThoughtsIdRoute: AppThoughtsIdRoute,
}

const AppThoughtsRouteWithChildren = AppThoughtsRoute._addFileChildren(
  AppThoughtsRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCapsulesRoute: typeof AppCapsulesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJournalRoute: typeof AppJournalRouteWithChildren
  AppLettersRoute: typeof AppLettersRouteWithChildren
  AppMemoriesRoute: typeof AppMemoriesRouteWithChildren
  AppMoodRoute: typeof AppMoodRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppPrivateRoute: typeof AppPrivateRoute
  AppScratchRoute: typeof AppScratchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppThoughtsRoute: typeof AppThoughtsRouteWithChildren
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFarewellCustomRoute: typeof AppFarewellCustomRoute
  AppFarewellVoiceRoute: typeof AppFarewellVoiceRoute
  AppTagsTagRoute: typeof AppTagsTagRoute
  AppFarewellIndexRoute: typeof AppFarewellIndexRoute
  AppFarewellEntityIdRoute: typeof AppFarewellEntityIdRoute
  AppFarewellPickCategoryRoute: typeof AppFarewellPickCategoryRoute
  AppFarewellPreviewEntityIdRoute: typeof AppFarewellPreviewEntityIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCapsulesRoute: AppCapsulesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppLettersRoute: AppLettersRouteWithChildren,
  AppMemoriesRoute: AppMemoriesRouteWithChildren,
  AppMoodRoute: AppMoodRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppPrivateRoute: AppPrivateRoute,
  AppScratchRoute: AppScratchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppThoughtsRoute: AppThoughtsRouteWithChildren,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppFarewellCustomRoute: AppFarewellCustomRoute,
  AppFarewellVoiceRoute: AppFarewellVoiceRoute,
  AppTagsTagRoute: AppTagsTagRoute,
  AppFarewellIndexRoute: AppFarewellIndexRoute,
  AppFarewellEntityIdRoute: AppFarewellEntityIdRoute,
  AppFarewellPickCategoryRoute: AppFarewellPickCategoryRoute,
  AppFarewellPreviewEntityIdRoute: AppFarewellPreviewEntityIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
